# SPDX-License-Identifier: Apache-2.0
---
# Splunk format tasks for redhatci.ocp.report_combine

- name: Create basic event structure
  ansible.builtin.set_fact:
    rc_event:
      test: "{{ rc_test_data }}"
      metadata: "{{ rc_meta_data }}"

- name: Set default metadata based event time
  ansible.builtin.set_fact:
    rc_event_time: >-
      {{
        (((rc_event.metadata.job.created_at.replace('Z', '+00:00') | to_datetime).timestamp() * 1000) | int / 1000.0) | string
      }}
  when:
    - rc_event_time | default('') | length == 0
    - rc_event.metadata.job is defined
    - rc_event.metadata.job.created_at | default('') | length > 0

- name: Generate fallback event time if metadata does not have it
  ansible.builtin.set_fact:
    rc_event_time: "{{ ansible_date_time.epoch }}.{{ '%03d' | format((ansible_date_time.microsecond | int / 1000) | int) }}"
  when:
    - rc_event_time | default('') | length == 0

- name: Ensure rc_event_time can be converted to a float
  ansible.builtin.assert:
    that:
      - rc_event_time | float is defined
    fail_msg: "Event time {{ rc_event_time }} cannot be converted to a float"

- name: Create Splunk-specific event payload
  ansible.builtin.set_fact:
    rc_combined_event:
      "source": "{{ rc_event_source }}"
      "event": "{{ rc_event }}"
      "host": "{{ rc_event_host }}"
      "sourcetype": "{{ rc_event_sourcetype }}"
      "time": "{{ rc_event_time | float }}"

- name: Print Splunk event structure
  ansible.builtin.debug:
    msg: "Created Splunk event with {{ rc_event.test.keys() | length }} test result keys and {{ rc_event.metadata.keys() | length }} metadata keys"
  when:
    - rc_debug
