# SPDX-License-Identifier: Apache-2.0
---
# tasks file main.yml for role junit2json

# NOTE: in case somebody did not install the collection properly, we test for filter's dependency

- name: Validate role variables
  ansible.builtin.assert:
    that:
      - junit2_input_reports_list | length > 0
      - junit2_output_dir | length > 0
    fail_msg: "One of the mandatory variables is missing or empty"

# During repeating tests, this variable needs to be reset each run
- name: Initialize reports variable
  ansible.builtin.set_fact:
    junit2_reports_list: []
    junit2_json_reports_list: []

- name: Print input reports variable
  ansible.builtin.debug:
    var: junit2_input_reports_list
    verbosity: 2

- name: Verify and junit2_input_reports_list and add existing files to junit2_reports_list
  ansible.builtin.include_tasks:
    file: verify-list.yml

- name: Convert XML reports to JSON
  ansible.builtin.include_tasks:
    file: convert-list.yml

- name: Handle jinja strings in data using dummy variables
  ansible.builtin.include_tasks:
    file: process-dummy.yml
  vars:
    j2j_dummy_var_action: set

- name: Merge JUnit XML reports into one file junit2_do_merge=true
  ansible.builtin.include_tasks:
    file: merge.yml
  when:
    - junit2_do_merge
    - junit2_json_reports_list | length > 0

- name: Handle jinja strings in data using dummy variables
  ansible.builtin.include_tasks:
    file: process-dummy.yml
  vars:
    j2j_dummy_var_action: clear
