---
- name: Wait until MachineConfigPool cluster gets updating state
  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"
  kubernetes.core.k8s_info:
    api: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: "{{ mcp_name }}"
  register: mcp_updating_status
  until: >
    (mcp_updating_status.resources | length > 0) and
    (
      ((mcp_updating_status.resources[0].status | default({})).conditions | default([]))
      | selectattr('type', 'equalto', 'Updating')
      | selectattr('status', 'equalto', 'True')
      | list
      | length
    ) > 0
  retries: 5
  delay: 20
  ignore_errors: true

- name: Fail if cluster mcp is not in progressing state
  ansible.builtin.fail:
    msg: Fail to wait until MachineConfig pool gets progressing state
  when:
    - mcp_updating_status is defined
    - mcp_updating_status.failed is true

- name: Wait until MachineConfigPool cluster gets updating state
  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"
  kubernetes.core.k8s_info:
    api: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
    name: "{{ mcp_name }}"
  register: mcp_updated_status
  until: >
    (mcp_updated_status.resources | length > 0) and
    (
      ((mcp_updated_status.resources[0].status | default({})).conditions | default([]))
      | selectattr('type', 'equalto', 'Updated')
      | selectattr('status', 'equalto', 'True')
      | list
      | length
    ) > 0
  retries: 30
  delay: 60
  ignore_errors: true

- name: Fail if cluster mcp is not in updated state
  ansible.builtin.fail:
    msg: Fail to wait until MachineConfig pool gets updated state
  when:
    - mcp_updated_status is defined
    - mcp_updated_status.failed is true
