---
- name: Apply Cgroup Version
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: Node
      metadata:
        name: cluster
      spec:
        cgroupMode: "{{ cgroup_version }}"
  when:
    # Test for v1 only on 4.16-4.18
    - cgroup_version == "v2" and ocp_version > "4.13" or
      cgroup_version == "v1" and ocp_version > "4.15" and ocp_version < "4.19"
  notify:
    - Wait for MCP
