---
- name: Change container runtime to {{ container_runtime }}
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: machineconfiguration.openshift.io/v1
      kind: ContainerRuntimeConfig
      metadata:
        name: "enable-{{ container_runtime }}-worker-cnf"
      spec:
        containerRuntimeConfig:
          defaultRuntime: "{{ container_runtime }}"
        machineConfigPoolSelector:
          matchLabels:
            machineconfiguration.openshift.io/role: worker-cnf
  when:
    - container_runtime == "crun" and ocp_version > "4.11" and ocp_version < "4.18" or
      container_runtime == "runc" and ocp_version > "4.16"
  notify:
    - Wait for MCP
