---
- name: Ensure python packages are installed
  ansible.builtin.pip:
    name:
      - kubernetes >= 24.2.0
      - PyYAML >= 3.11

- name: Get Cluster version
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: api_version

- name: Set ocp_version
  ansible.builtin.set_fact:
    ocp_version: "{{ api_version.resources[0].status.desired.version.split('.')[:2] | join('.') }}"

- name: Print ocp_version
  ansible.builtin.debug:
    msg: "OCP version: {{ ocp_version }}"

- name: Create machine config pool
  ansible.builtin.include_tasks: machineConfigPool.yml

- name: Apply Cgroup configuration
  ansible.builtin.include_tasks: cgroup.yml
  when: cgroup_version is defined

- name: Apply container runtime config
  ansible.builtin.include_tasks: containerRuntime.yml
  when: container_runtime is defined

- name: Create performance Profile
  ansible.builtin.include_tasks: ppc.yml
