---
mcp_timeout: 10m
artifacts_folder: /artifacts
ignore_cgroups_version: "true"
rt_kernel: false
high_power_consumption: false
per_pod_power_management: false
must_gather_dir: "/mustgather"
container_runtime: "runc"

mcp_wait_retries: 180
mcp_wait_delay: 30
