---
- name: Wait for MCP
  block:
    - name: Wait for MCP to start
      kubernetes.core.k8s_info:
        api_version: machineconfiguration.openshift.io/v1
        kind: MachineConfigPool
        name: "worker-cnf"
      register: mcp_restart
      until: >
        mcp_restart.resources is defined and
        mcp_restart.resources | length > 0 and
        mcp_restart.resources[0].status.updatedMachineCount != mcp_restart.resources[0].status.machineCount
      retries: 6
      delay: 10
      vars:
        ansible_failed_result:
          retries: 0
      ignore_errors: true
      listen: Wait for MCP

    - name: Wait until the MCP is fully updated
      kubernetes.core.k8s_info:
        api_version: machineconfiguration.openshift.io/v1
        kind: MachineConfigPool
        name: "worker-cnf"
      register: mcp_status
      until: >
        mcp_status.resources is defined and
        mcp_status.resources | length > 0 and
        mcp_status.resources[0].status.updatedMachineCount == mcp_status.resources[0].status.machineCount and
        mcp_status.resources[0].status.degradedMachineCount == 0
      retries: "{{ mcp_wait_retries }}"
      delay: "{{ mcp_wait_delay }}"
      vars:
        ansible_failed_result:
          retries: 0
      listen: Wait for MCP
