---
- name: Set OperatorGroup spec configuration
  ansible.builtin.set_fact:
    operator_group_spec_config: >-
      {{
        operator_item.og_spec | default({'targetNamespaces': [operator_item.nsname]})
      }}

- name: Deploy operator via olm
  tags:
    - skip_ansible_lint
  ansible.builtin.include_role:
    name: redhatci.ocp.olm_operator
  vars:
    operator: "{{ operator_item.name }}"
    source: "{{ operator_item.catalog }}"
    namespace: "{{ operator_item.nsname }}"
    operator_group_name: "{{ operator_item.og_name | default(operator_item.name) }}"
    channel: "{{ operator_item.channel | default('') }}"
    ns_labels:
      "{{ operator_item.ns_labels | default(ocp_operator_deployment_default_label) }}"
    operator_group_spec: "{{ operator_group_spec_config }}"
    starting_csv: "{{ operator_item.starting_csv | default('') }}"
    subscription_name: "{{ operator_item.subscription_name | default(undefined) }}"
    install_approval: "{{ operator_item.install_approval | default('Automatic') }}"

- name: Apply default operator configuration if exist
  kubernetes.core.k8s:
    template: "{{ role_path }}/templates/{{ operator_item.name }}-config.j2"
    state: present
    force: true
  register: result
  when:
    - operator_item.deploy_default_config is defined
    - operator_item.deploy_default_config
